version: '3.8'

services:
  ms-notifications:
    build: .
    container_name: service-notifications
    labels:
      logging: "enabled"
      service: "service-notifications"
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb-notifications:27017/hubertapp_notifications
      - OTEL_SERVICE_NAME=service-notifications
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=none
    env_file:
      - .env
    networks:
      - hubert-network
    depends_on:
      mongodb-notifications:
        condition: service_started

  mongodb-notifications:
    image: mongo:latest
    container_name: mongodb-notifications-container
    ports:
      - "27018:27017"
    volumes:
      - mongo_notifications_data:/data/db
    networks:
      - hubert-network

volumes:
  mongo_notifications_data:

networks:
  hubert-network:
    external: true