version: '3.8'

services:
  ms-notifications:
    build: .
    container_name: service-notifications
    ports:
      - "3002:3001" 
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017/hubertapp_notifications

    env_file:
      - .env
    networks:
      - hubert-network
    depends_on:
      mongodb:
        condition: service_started

  mongodb:
    image: mongo:latest
    container_name: mongodb-notifications-container
    ports:
      - "27018:27017"
    volumes:
      - mongo_notifications_data:/data/db
    networks:
      - hubert-network

volumes:
  mongo_notifications_data:

networks:
  hubert-network:
    external: true