name: "CI Work branches"

on:
  push:
    branches-ignore:
      - 'main'
      - 'develop'
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install and Lint
        run: |
          make install
          make lint